### ISSUE TITLE
possible to get all values in a path?

### ISSUE THREAD

**Issue by leshow** [sile/patricia_tree#4]
would it be possible to traverse the tree using a key, picking up all of the matching values in the path?

Something like this:
```
use patricia_tree::PatriciaMap;

fn main() {
    let mut t = PatriciaMap::new();
    t.insert("z", vec!["z"]);
    t.insert("aba", vec!["a"]);
    t.insert("abb", vec!["b"]);
    t.insert("abc", vec!["c"]);

    assert!(t.get_all_in(&"abd").eq(vec!["a", "b", "c"].iter()));
}
```
we walk along the tree using the key, gathering up the matches as we go, when it no longer matches, return the gathered results

**Comment by sile** [comment]
I think that there is not a dedicated method for such a purpose. To realize it only using the existing API, you might be able to write code as follows:
```rust
use patricia_tree::PatriciaMap;

fn main() {
    let mut t = PatriciaMap::new();
    t.insert("z", vec!["z"]);
    t.insert("aba", vec!["a"]);
    t.insert("abb", vec!["b"]);
    t.insert("abc", vec!["c"]);

    let values = t
        .iter()
        .take_while(|(k, _)| k.as_slice() <= &b"abd"[..])
        .flat_map(|(_, v)| v.into_iter());
    assert!(values.eq(vec!["a", "b", "c"].iter()));
}
```

**Comment by leshow** [comment]
Right, the `iter` produced there will be an iterator over ALL values in the map though? Potentially the map is very large, and I'm concerned about iterating all values and doing a string comparison.

I've noticed some other radix libraries seem to provide a `get_descendents` fn, or something like that. How would you go about adding that kind of method? Are you interested in getting it back upstream if I add it?

**Comment by sile** [comment]
Thank you for the clarification, but I'm still a bit confusing.
The new example code you wrote seems to iterate over the elements whose keys match with a prefix of the given key (i.e., "abc"). So it seems to get the `ancient` elements of the key rather than the `descendent` ones to me. Please let me know if I misunderstood something.

> Are you interested in getting it back upstream if I add it?

Sure. It's very welcomed!

The implementation code for the following methods may be helpful when you implement the feature.
- [PatriciaMap.iter_prefix](https://docs.rs/patricia_tree/0.1.9/patricia_tree/map/struct.PatriciaMap.html#method.iter_prefix)
- [PatriciaMap.get_longest_common_prefix](https://docs.rs/patricia_tree/0.1.9/patricia_tree/map/struct.PatriciaMap.html#method.get_longest_common_prefix)
- [PatriciaMap.split_by_prefix](https://docs.rs/patricia_tree/0.1.9/patricia_tree/map/struct.PatriciaMap.html#method.split_by_prefix)

**Comment by leshow** [comment]
Sure, maybe `descendants` is the wrong term, I just want to gather everything along a certain path up until things stop matching. This could be accomplished by walking the tree each time for `a` `ab` `abc` separately, but ideally, we'd only have to walk the tree one time and could collect all the elements at once.

**Comment by sile** [comment]
Got it, thanks. I think that it's a useful feature to be worth implementing.

**Comment by leshow** [comment]
I've been messing around with this the better part of today, I think I've got something that works. I wrote it first just as a method that accepts `&mut Vec<&V>`, then again as an iterator implementation. I still need to do some more tests.

While I was modifying things, I noticed there are iterators that return the keys as `Vec<u8>` for each value iterated. It's possible, I think, to skip this allocation on items by giving the full key to the iterator instance first, then tracking the lifetimes through.

```
pub struct CollectIter<'a, 'b, V: 'a> {
    key: &'b [u8],
    stack: Vec<(usize, usize, &'a Node<V>)>, // (level, key offset, node)
}

impl<'a, 'b, V: 'a> Iterator for CollectIter<'a, 'b, V> {
...
}
```

One downside of this, is that you can't use `K: AsRef<[u8]> + 'b` as a parameter for the key, you have to have like `&'b K` or `&'b [u8]`, afaik. Anyway, this would be a breaking change, but would most likely make iteration faster by removing the need to allocate each key entry
